//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.StepInLifeService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistrationErrors", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    public enum RegistrationErrors : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordStrength = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownError = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StepInLifeService.IContract")]
    public interface IContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContract/InsertCheck", ReplyAction="http://tempuri.org/IContract/InsertCheckResponse")]
        Client.StepInLifeService.RegistrationErrors InsertCheck(string name, string surname, System.DateTime birthday, string specialization, string email, string password, string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContract/InsertCheck", ReplyAction="http://tempuri.org/IContract/InsertCheckResponse")]
        System.Threading.Tasks.Task<Client.StepInLifeService.RegistrationErrors> InsertCheckAsync(string name, string surname, System.DateTime birthday, string specialization, string email, string password, string city);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContractChannel : Client.StepInLifeService.IContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContractClient : System.ServiceModel.ClientBase<Client.StepInLifeService.IContract>, Client.StepInLifeService.IContract {
        
        public ContractClient() {
        }
        
        public ContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.StepInLifeService.RegistrationErrors InsertCheck(string name, string surname, System.DateTime birthday, string specialization, string email, string password, string city) {
            return base.Channel.InsertCheck(name, surname, birthday, specialization, email, password, city);
        }
        
        public System.Threading.Tasks.Task<Client.StepInLifeService.RegistrationErrors> InsertCheckAsync(string name, string surname, System.DateTime birthday, string specialization, string email, string password, string city) {
            return base.Channel.InsertCheckAsync(name, surname, birthday, specialization, email, password, city);
        }
    }
}
